import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import LayoutClient from "./LayoutClient";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{backgroundRepeat: 'no-repeat', backgroundImage: "url('/images/bg.jpg')", backgroundBlendMode: 'hard-light', backgroundSize: 'cover', backgroundPosition: 'center'}}
      >
          <AppRouterCacheProvider>
            <LayoutClient>{children}</LayoutClient>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
